CREATE TABLE categoria (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    Categoria Varchar(25)
);

CREATE TABLE estrelas (
    ID_STAR INT AUTO_INCREMENT PRIMARY KEY,
    AVALIACAO VARCHAR (45)
);


CREATE TABLE obras (
    ID_OBRA INT AUTO_INCREMENT PRIMARY KEY,
    Nome Varchar(50),
    Lancamento Date,
    Autor Varchar(30),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria(ID_CATEGORIA),
    Sinopse text,
    ID_STAR INT,
    FOREIGN KEY (ID_STAR) REFERENCES estrelas(ID_STAR),
    Foto varchar(255),
    Tipo INT
);


CREATE TABLE avaliacoes (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO TEXT,
    ID_OBRA INT,
    FOREIGN KEY(ID_OBRA) REFERENCES obras(ID_OBRA),
    ID_STAR INT,
    FOREIGN KEY(ID_STAR) REFERENCES estrelas(ID_STAR)
);

ALTER TABLE obras ADD COLUMN ID_AVALIACAO INT, ADD CONSTRAINT FK_AVALIACOES FOREIGN KEY (ID_AVALIACAO) REFERENCES avaliacoes (ID_AVALIACAO)